steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dev-project-243100/gcp_cloud_function_poc:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dev-project-243100/gcp_cloud_function_poc:$SHORT_SHA']
